title="FHIR/OMOP VKG Demo"

[defaultTab]
query="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX w5: <http://hl7.org/fhir/w5#>

SELECT * WHERE {
    # ?x a fhir:DomainResource .
    ?x a fhir:Patient .
	?x fhir:Resource.id [fhir:value ?id] 
} 
LIMIT 100
"""

[[tabGroups]]

name="Example Queries"

[[tabGroups.tabs]]

name="Patient"
query="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX w5: <http://hl7.org/fhir/w5#>

SELECT * WHERE {
    ?sub a fhir:Patient .
    ?sub fhir:Patient.gender    [   fhir:value ?gender      ] .
    ?sub fhir:Patient.birthDate [   fhir:value ?birthDate   ] .
} 
LIMIT 10
"""

[[tabGroups.tabs]]
name="DESCRIBE a Patient"
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX w5: <http://hl7.org/fhir/w5#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DESCRIBE ?p ?o
WHERE {
    ?p a fhir:Patient ; fhir:Resource.id [ fhir:value "392776922" ]  .
  	?p ?e ?o .
}
"""

[[tabGroups.tabs]]

name="Condition"
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX w5: <http://hl7.org/fhir/w5#>

SELECT DISTINCT ?patient ?code ?system ?display WHERE {
    ?condition a fhir:Condition .
 	?condition	fhir:Condition.subject	?patient .
	?condition	fhir:Condition.code	[
	    fhir:CodeableConcept.coding [ 
            fhir:Coding.code    [ fhir:value    ?code    ];  
            fhir:Coding.system  [ fhir:value    ?system  ]; 
            fhir:Coding.display [ fhir:value    ?display ] 
	    ] 
	].
	FILTER (str(?code) = '129721000119106' || str(?code) = '140031000119103' || str(?code) = '145681000119101' || str(?code) = '14669001' || str(?code) = '200118004' || str(?code) = '236428007' || str(?code) = '236429004' || str(?code) = '236432001' || str(?code) = '307309005' || str(?code) = '36225005' || str(?code) = '423533009' || str(?code) = '429224003' || str(?code) = '429489008' || str(?code) = '430535006' || str(?code) = '722095005' || str(?code) = '722096006' || str(?code) = '722278006'  )
	FILTER (str(?system) = 'SNOMED' )
}
LIMIT 100
"""

[[tabGroups.tabs]]
name="Condition - Count"
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX w5: <http://hl7.org/fhir/w5#>

SELECT DISTINCT ?code ?system ?display (count(?patient) as ?count) WHERE {
    ?condition a fhir:Condition .
 	?condition	fhir:Condition.subject	?patient .
	?condition	fhir:Condition.code	[
	    fhir:CodeableConcept.coding [ 
	        fhir:Coding.code	[ fhir:value	?code    ];  
	        fhir:Coding.system	[ fhir:value	?system  ]; 
	        fhir:Coding.display	[ fhir:value	?display ] 
        ] 
    ].
	FILTER (str(?code) = '129721000119106' || str(?code) = '140031000119103' || str(?code) = '145681000119101' || str(?code) = '14669001' || str(?code) = '200118004' || str(?code) = '236428007' || str(?code) = '236429004' || str(?code) = '236432001' || str(?code) = '307309005' || str(?code) = '36225005' || str(?code) = '423533009' || str(?code) = '429224003' || str(?code) = '429489008' || str(?code) = '430535006' || str(?code) = '722095005' || str(?code) = '722096006' || str(?code) = '722278006'  )
	FILTER (str(?system) = 'SNOMED' )
} GROUP BY ?code ?system ?display ORDER BY ?count
"""

[[tabGroups.tabs]]
name="Condition"
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX w5: <http://hl7.org/fhir/w5#>

SELECT DISTINCT ?patient ?code ?system ?display WHERE {
{
    ?condition a fhir:Condition .
 	?condition	fhir:Condition.subject	?patient .
	?condition	fhir:Condition.code	[
	    fhir:CodeableConcept.coding [
	        fhir:Coding.code	[ fhir:value	?code  ];  
	        fhir:Coding.system	[ fhir:value	?system  ]; 
	        fhir:Coding.display	[ fhir:value	?display  ] 
        ] 
    ].
	FILTER (str(?code) = '1532007' || str(?code) = '195655000' || str(?code) = '195656004' || str(?code) = '195657008' || str(?code) = '195658003' || str(?code) = '195659006' || str(?code) = '195660001' || str(?code) = '195662009' || str(?code) = '232399005' || str(?code) = '232400003' || str(?code) = '363746003' || str(?code) = '40766000' || str(?code) = '43878008' || str(?code) = '58031004' || str(?code) = 'J02.0' || str(?code) = 'J02.8' || str(?code) = 'J02.9'  )
	FILTER (str(?system) = 'SNOMED' || str(?system) = 'ICD10CM' )
}
UNION
{
 	?condition a fhir:Condition .
    ?condition	fhir:Condition.subject	?patient .
	?condition	fhir:Condition.code	[
	    fhir:CodeableConcept.coding [ 
	        fhir:Coding.code	[ fhir:value	?code  ];  
	        fhir:Coding.system	[ fhir:value	?system  ]; 
	        fhir:Coding.display	[ fhir:value	?display  ] 
        ] 
    ].	
    FILTER (str(?code) = '10629271000119107' || str(?code) = '17741008' || str(?code) = '195666007' || str(?code) = '195668008' || str(?code) = '195669000' || str(?code) = '195670004' || str(?code) = '195671000' || str(?code) = '195672007' || str(?code) = '195673002' || str(?code) = '195676005' || str(?code) = '195677001' || str(?code) = '302911003' || str(?code) = 'J03.00' || str(?code) = 'J03.01' || str(?code) = 'J03.80' || str(?code) = 'J03.81' || str(?code) = 'J03.90' || str(?code) = 'J03.91'  )
	FILTER (str(?system) = 'SNOMED' || str(?system) = 'ICD10CM' )
}
}
"""

[[tabGroups.tabs]]
name="Practitioner"
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX w5: <http://hl7.org/fhir/w5#>

SELECT DISTINCT * WHERE {
    ?p a   fhir:Practitioner .
	OPTIONAL {?p  fhir:Resource.id                [ fhir:value ?id ]  .}
	OPTIONAL {?p  fhir:Practitioner.identifier    [ fhir:value ?identifier ] }
	OPTIONAL {?p  fhir:Practitioner.name          [ fhir:value ?name ]  .}
	OPTIONAL {?p  fhir:Practitioner.gender        ?gender  . }
	OPTIONAL {?p  fhir:Practitioner.birthDate     [ fhir:value ?birth_date ] . }                               
	OPTIONAL {?p  fhir:Practitioner.qualification [ fhir:Practitioner.qualification.identifier [ fhir:Identifier.value [ fhir:value ?qualification ] ] ]  .}
}
LIMIT 100
"""
[[tabGroups.tabs]]
name="Procedure"
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX w5: <http://hl7.org/fhir/w5#>

DESCRIBE ?p ?o WHERE {
    ?p a   fhir:Procedure .
	?p  fhir:Resource.id  [ fhir:value "330854196" ]  .
    ?p ?e ?o
}
"""

[[tabGroups.tabs]]
name="Encounter"
query="""
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX w5: <http://hl7.org/fhir/w5#>

DESCRIBE ?p ?o WHERE {
    ?p a   fhir:Encounter .
	?p  fhir:Resource.id  [ fhir:value "541" ]  .
  ?p ?e ?o
}
"""

[[tabGroups.tabs]]
name="ConceptMap (subsumes)"
query="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX w5: <http://hl7.org/fhir/w5#>

SELECT * WHERE {
	?map a fhir:ConceptMap ;
	    fhir:ConceptMap.sourceUri ?source ;
	    fhir:ConceptMap.targetUri ?target ;
	    fhir:ConceptMap.group.element.target.equivalence [fhir:value "subsumes"] .
	?source fhir:CodeableConcept.coding [  fhir:Coding.code    [ fhir:value ?source_code ] ;
                                           fhir:Coding.display [ fhir:value ?source_name ]  ;
                                           fhir:Coding.system  [ fhir:value ?source_system ]  ; ] ;
		    fhir:CodeableConcept.text   [ fhir:value  ?source_text]  .
	?target fhir:CodeableConcept.coding [  fhir:Coding.code    [ fhir:value ?target_code ] ;
                                           fhir:Coding.display [ fhir:value ?target_name ]  ;
                                           fhir:Coding.system  [ fhir:value ?target_system ]  ; ] ;
		    fhir:CodeableConcept.text   [ fhir:value  ?target_text]  .
    FILTER(?source != ?target)
    FILTER(?source_system != ?target_system) 
} 
LIMIT 100
"""